### ISSUE TITLE
Fix Dancify Inference

### ISSUE THREAD

**Issue by ExponentialML** [haofanwang/visbeat3#3]
Dancify wasn't working for me, but I found the issue in my case. 
There's a bug with the new update that doesn't allow Dancify to run properly. This fixes it.

Change this:

https://github.com/haofanwang/visbeat3/blob/4714076cb93383bb44869bca2875a829b68d84b2/visbeat3/Image.py#L32

To True:

```python
USING_OPENCV=True;
```

It could also be removed because OpenCV seems to be a prerequisite, but doing so may also break the install.

**Comment by haofanwang** [comment]
@ftaker887 Thanks for your info, I'll add OpenCV and make an update soon.
