### ISSUE TITLE
Fix imageio-ffmpeg bug with Dancify inference

### ISSUE THREAD

**Issue by ExponentialML** [haofanwang/visbeat3#4]
I was getting this error after Dancify inference. A series of errors were as follows:

```bash
Fatal Python error: could not acquire lock for <_io.BufferedReader name=11> at interpreter shutdown, possibly due to daemon threads
```

This was due to a bug with imageio-ffmpeg not being the latest version, or not being installed.

```bash
pip install imageio-ffmpeg --upgrade # If already installed
```

**Comment by haofanwang** [comment]
This issue is caused by imageio. I will update in the latest version.
