### ISSUE TITLE
Function to get the video spectrogram

### ISSUE THREAD

**Issue by SutirthaChakraborty** [haofanwang/visbeat3#5]
Can we extract the video spectrogram using a function directly into a numpy array?

**Comment by haofanwang** [comment]
I haven't add new functions into this project yet.

I think you can achieve this by 

```
import visbeat3 as vb

video = vb.PullVideo(name='video_name', source_location='./data/01.mp4')
audio = video.getAudio()
spectrogram  = audio.getSpectrogram()
```

**Comment by haofanwang** [comment]
Please open a new issue for further question. Closed.
